version: '3.4'

services:
  fc.codeflix.catalog.db:
    container_name: catalogdb
    image: mysql
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: C0D3fl1x.@
        MYSQL_DATABASE: codeflix
networks:
  default:
      name: service_catalog